server:
  port: 0

spring:
  application:
    name: project-service
  datasource:
    url: jdbc:postgresql://localhost:5432/project_service_db
    username: ${JDBC_USERNAME_LOCALHOST}
    password: ${JDBC_PASSWORD_LOCALHOST}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false

  security:
    oauth2:
      resourceserver:
        jwt:
          pass:

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: aMinhaChaveSuperSecretaParaJWT32

logging:
  level:
    org.springframework.security: DEBUG
    com.microservice.clientes.Clientes_microservice_curse: DEBUG
    org.springframework.cloud.gateway: TRACE
